### ISSUE TITLE
ReferenceError cordova is not defined

### ISSUE THREAD

**Issue by hitteshahuja** [moodlehq/moodlemobile2#217]
Tried to follow instrutctions given here : https://docs.moodle.org/dev/Setting_up_your_development_environment_for_Moodle_Mobile_2

but i keep getting "cordova is not defined" when trying to connect to moodle.
![screen shot 2015-09-10 at 18 55 24](https://cloud.githubusercontent.com/assets/2855029/9796429/08432fc6-57ee-11e5-9eb0-9b26e2c2ec28.png)

**Comment by dpaloucva** [comment]
Hi,

we've identified this error and we've opened an issue to fix it:

https://tracker.moodle.org/browse/MOBILE-1219

Thanks,
Dani

**Comment by carloscallahuayapa** [comment]
Hello, I Tried to follow instrutctions, but I have this problem, please help me.  Thanks :)
![moodle_error](https://cloud.githubusercontent.com/assets/8115353/10422479/93df9c2c-7080-11e5-8a97-61a64015ef22.PNG)

**Comment by jleyva** [comment]
Closing this issue, please follow-up in the tracker
