### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by itfutures** [moodlehq/moodlemobile2#276]
![image](https://cloud.githubusercontent.com/assets/15669261/11009953/7ba14bb0-852f-11e5-93a0-513f27cde151.png)

**Comment by dpalou** [comment]
Hi,

if you see the strings like this it probably means that you don't have angular-translate installed. If you want to develop a custom version of the app please make sure to follow all the steps in this page:

https://docs.moodle.org/dev/Setting_up_your_development_environment_for_Moodle_Mobile_2

Kind regards,
Dani
