### ISSUE TITLE
Android version getting connect error

### ISSUE THREAD

**Issue by srinathvsp** [moodlehq/moodlemobile2#280]
hi,
am not able to connect from initial page to login page its keep on loading only y? can any one suggest

**Comment by dpalou** [comment]
Hi,

does this error happen with the app downloaded from Google Play or you built your own version?

Regards,
Dani

**Comment by srinathvsp** [comment]
not from google play its from my built

**Comment by srinathvsp** [comment]
ios working fine but android not able to connect from initial page to login but its showing loading

**Comment by srinathvsp** [comment]
yes i got because of cordova network plug-in is not install after install am getting this "Error: Cannot connect: the site must use Moodle 2.4 or later". but in ios what ever url using same using in android but ios able to use that url but in android not possible y

**Comment by dpalou** [comment]
If you're bulding using the command line (NOT PhoneGap Build) please make sure to follow all the steps in the following guide: https://docs.moodle.org/dev/Setting_up_your_development_environment_for_Moodle_Mobile_2

Also, can you check that you have the plugin cordova-plugin-whitelist installed?

**Comment by jleyva** [comment]
Closing this issue:
For general questions refer to: https://moodle.org/mod/forum/view.php?id=7798
For bugs: https://tracker.moodle.org/projects/MOBILE
